version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: user_management
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/my.cnf:/etc/mysql/my.cnf

  backend:
    build: ./backend
    container_name: backend_service
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html

volumes:
  db_data:
